export const PERMACAST_CONTRACT_ADDRESS = `zVgwbAUeYaYeZiRnv1Lqg4yLELC7OXsPDMhdfmQHTG4`;
export const PASOM_CONTRACT_ADDRESS = `RwH6UF6fmmCZrtYAu0HKc-_sK31RHlRZThutK0PD5_Y`;
export const ANS_CONTRACT_ADDRESS = `VGWeJLDLJ9ify3ezl9tW-9fhB0G-GIUd60FE-5Q-_VI`;
